07_django/review_prj/board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index),
    path('greeting/<str:name>/<str:role>', views.greeting),

    # Create
    # /articles/new => html (새로 작성하는 화면)
    path('articles/new/', views.article_new),
    # /articles/creat => DB new record
    path('articles/create/', views.article_create),

    # Read
    # /articles => html (all articles)
    path('articles/', views.article_list),
    # /articles/1 => html (article with id 1)
    path('articles/<int:id>/', views.article_detail),

    # Update
    # /articles/1/edit => html (article id=1 수정하는 화면)
    path('articles/<int:id>/edit/', views.article_edit),
    # /articles/1/update => DB update article id=1
    path('articles/<int:id>/update/', views.article_update),

    # Delete
    # /articles/1/delete => DB delete article id=1
    path('articles/<int:id>/delete/', views.article_delete),

]

07_django/review_prj/board_ad/urls.py
from django.urls import path
from . import views

app_name = 'board_ad'

urlpatterns = [
    # Create
    path('new/', views.create_posting, name='create_posting'),
    # Read
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    # Update
    path('<int:posting_id>/edit/', views.update_posting, name='update_posting'),
    # Delete
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),

    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'), # DOMAIN/postings/1/comments/create
    path('<int:posting_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'), # /postings/1/comments/1/delete

]

07_django/review_prj/review_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # /board_ad 로 시작하는 URL은 전부 board_ad/urls.py 로 보내라.
    path('board_ad/', include('board.urls')),
    path('postings/', include('board_ad.urls')),
]

07_django/review_prj/board/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return f'{self.id}: {self.title}'

07_django/review_prj/board_ad/models.py
from django.db import models

# Create your models here.


class Posting(models.Model):
    title = models.CharField(max_length=200, default='')
    content = models.TextField(default='Default CONTENT')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:30]}'

07_django/review_prj/board/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
# id 불필요
def article_new(request):
    return render(request, 'board/new.html')

def article_create(request):
    article = Article()
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()
    return redirect(f'/board_ad/articles/{article.id}')

def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {'articles': articles})


# id 필요
def article_detail(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'board/detail.html', {'article': article})

def article_edit(request, id):
    article = Article.objects.get(id=id)
    return render(request, 'board/edit.html', {'article': article})

def article_update(request, id):
    article = Article.objects.get(id=id)
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()
    return redirect(f'/board_ad/articles/{article.id}/')

def article_delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('/board_ad/articles/')














def index(request):
    return render(request, 'board/index.html')

def greeting(request, name, role):
    if name == 'admin':
        return render(request, 'board/greeting.html', {'role': 'MASTER USER', 'name': name.upper()})
    else:
        return render(request, 'board/greeting.html', {'role': role, 'name': name})

07_django/review_prj/board_ad/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from .models import Posting, Comment

# Posting
# Create
@require_http_methods(['GET', 'POST'])
def create_posting(request):
    if request.method == 'POST':
        posting = Posting()
        posting.title = request.POST.get('title')
        posting.content = request.POST.get('content')
        posting.save()
        return redirect('board_ad:posting_detail', posting_id=posting.id)
    else:
        return render(request, 'board_ad/new.html')


# Read
@require_http_methods(['GET'])
def posting_list(request):
    postings = Posting.objects.all()
    return render(request, 'board_ad/list.html', {'postings': postings})


@require_http_methods(['GET'])
def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all()
    return render(request, 'board_ad/detail.html', {'posting': posting, 'comments': comments})


# Update
@require_http_methods(['GET', 'POST'])
def update_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method == 'POST':
        posting.title = request.POST.get('title')
        posting.content = request.POST.get('content')
        posting.save()
        return redirect('board_ad:posting_detail', posting_id=posting.id)
    else:
        return render(request, 'board_ad/edit.html', {'posting': posting})


# Delete
@require_http_methods(['POST'])
def delete_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    posting.delete()
    return redirect('board_ad:posting_list')


# Comment - Create
@require_http_methods(['POST'])
def create_comment(request, posting_id):
    comment = Comment()
    comment.content = request.POST.get('comment')
    comment.posting = get_object_or_404(Posting, id=posting_id)
    comment.save()
    return redirect('board_ad:posting_detail', posting_id=posting_id)


@require_http_methods(['POST'])
def delete_comment(request, posting_id, comment_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('board_ad:posting_detail', posting_id=posting.id)

07_django/review_prj/board_ad/templates/board_ad/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

07_django/review_prj/board_ad/templates/board_ad/detail.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>{{ posting.title }}</h1>
    <p>
        {{ posting.content }}
    </p>
    <hr>
    <a href="{% url 'board_ad:posting_list' %}"><button>List</button></a>
    <a href="{% url 'board_ad:update_posting' posting.id %}"><button>Edit</button></a>
    <form action="{% url 'board_ad:delete_posting' posting.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('진짜 지울거야?');">Delete</button>
    </form>

    <button id="reset_button">WOW</button>
    <script>
        button = document.querySelector('#reset_button');
        button.addEventListener('click', (e) => {
            document.write('<h1>hahah</h1>');
        });
    </script>

    <hr>
    <section>
        {% if comments %}
            <ul>
                {% for comment in comments %}
                    <li>
                        {{ comment.content }}
                        <form action="{% url 'board_ad:delete_comment' posting.id comment.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit">댓글삭제</button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>

    <form action="{% url 'board_ad:create_comment' posting.id %}" method="POST">
        {% csrf_token %}
        <label for="comment">comment:</label>
        <input type="text" name="comment" id="comment">
        <button type="submit">댓글 쓰기</button>
    </form>
{% endblock %}

07_django/review_prj/board_ad/templates/board_ad/edit.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>Edit Posting</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="input_title">Title:</label>
            <input name="title" id="input_title" type="text" value="{{ posting.title }}">
        </div>
        <div>
            <label for="input_content">Content:</label>
            <textarea name="content" id="input_content" cols="30" rows="10">{{ posting.content }}</textarea>
        </div>
        <div>
            <button type="submit">UPDATE!</button>
        </div>
    </form>
{% endblock %}

07_django/review_prj/board_ad/templates/board_ad/greeting.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>Hello {{ name }}</h1>
    <h2>You are {{ role }}</h2>
{% endblock %}

07_django/review_prj/board_ad/templates/board_ad/index.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>This is INDEX page</h1>
{% endblock %}

07_django/review_prj/board_ad/templates/board_ad/list.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>Article LIST</h1>
    <a href="{% url 'board_ad:create_posting' %}"><button>New Article</button></a>
    {% if postings %}
    <ul>
        {% for posting in postings %}
            <li>
                <a href="{% url 'board_ad:posting_detail' posting.id %}">{{ posting.title }}</a>
            </li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

07_django/review_prj/board_ad/templates/board_ad/new.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>New Posting</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="input_title">Title:</label>
            <input name="title" id="input_title" type="text">
        </div>
        <div>
            <label for="input_content"></label>
            <textarea name="content" id="input_content" cols="30" rows="10"></textarea>
        </div>
        <div>
            <button type="submit">CREATE!</button>
        </div>
    </form>
{% endblock %}