testPractice/testA/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

testPractice/testA/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('<int:post_id>/edit/', views.update_post, name='update_post'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
]

testPractice/testA/testA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

testPractice/testA/accounts/models.py
from django.db import models

# Create your models here.

testPractice/testA/posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140, default='')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

testPractice/testA/posts/forms.py
from django import forms
from .models import Post


class PostModelForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['content', ]

testPractice/testA/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:post_list')

    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


@require_http_methods(['GET', 'POST'])
def log_in(request):
    if request.user.is_authenticated:
        return redirect('posts:post_list')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'posts:post_list')

    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


@login_required
def log_out(request):
    auth_logout(request)
    return redirect('posts:post_list')

testPractice/testA/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_GET
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostModelForm


# Create your views here.
@require_http_methods(['GET', 'POST'])
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'posts/list.html', {'posts': posts})


@login_required
@require_http_methods(['GET', 'POST'])
def create_post(request):
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:post_list')

    else:
        form = PostModelForm()

    return render(request, 'posts/form.html', {'form': form})


@login_required
@require_http_methods(['GET', 'POST'])
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user == request.user:
        if request.method == 'POST':
            form = PostModelForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:post_list')

        else:
            form = PostModelForm(instance=post)
    else:
        return redirect('posts:post_list')

    return render(request, 'posts/edit.html', {'form': form})


@require_POST
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('posts:post_list')


@login_required
@require_POST
def toggle_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)

    return redirect('posts:post_list')

testPractice/testA/accounts/templates/accounts/login.html
{% extends 'posts/base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>
{% endblock %}

testPractice/testA/accounts/templates/accounts/signup.html
{% extends 'posts/base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>
{% endblock %}

testPractice/testA/posts/templates/posts/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

testPractice/testA/posts/templates/posts/edit.html
{% extends 'posts/base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">수정하기</button>
    </form>

{% endblock %}

testPractice/testA/posts/templates/posts/form.html
{% extends 'posts/base.html' %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">제출</button>
    </form>
{% endblock %}

testPractice/testA/posts/templates/posts/list.html
{% extends 'posts/base.html' %}

{% block body %}
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    <hr>
    {% if posts %}
        <div>
            {% for post in posts %}
                {{ post.content }}
                좋아요 : {{ post.like_users.all.count }}
                <div>
                    작성자 : {{ post.user.username }}
                </div>
                <form action="{% url 'posts:toggle_like' post.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">좋아요</button>
                </form>
                <a href="{% url 'posts:update_post' post.id %}">
                    <button>수정하기</button>
                </a>
                {% if post.user == request.user %}
                    <form action="{% url 'posts:delete_post' post.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">삭제하기</button>
                    </form>
                {% endif %}
            {% endfor %}
        </div>

    {% endif %}
    <hr>
    <div>
        <a href="{% url 'posts:create_post' %}">
            <button>새 글</button>
        </a>
    </div>
{% endblock %}