07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),

    path('users/<str:username>/', views.user_detail, name='user_detail'),
    path('follow/<str:username>/', views.toggle_follow, name='toggle_follow'),
]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

# Media Upload
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insta/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#if env dev => [...]
#if env prod => None
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/update/', views.update_post, name='update_post'),
    path('<int:post_id>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    # /insta/tags/hihi => #hihi 포함한 모든 posts 보기
    path('tags/<str:tag_name>/', views.tag_posts_list, name='tag_posts_list'),
]

07_django/INSTA/posts/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
from faker import Faker
faker = Faker()
# import os
#
# ENV = os.environ.get('ENVIRONMENT', 'development')
# if ENV == 'development':
#     from IPython import embed
#     from faker import Faker


# Create your models here.
class HashTag(models.Model):
    content = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.content


class Post(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    tags = models.ManyToManyField(HashTag, blank=True, related_name='posts')

    @classmethod
    def dummy(cls, n):
        for _ in range(n):
            Post.objects.create(content=faker.text(120))


class Image(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        blank=True,
        upload_to='posts/images',
        processors=[ResizeToFill(600, 600)],
        format='JPEG',
        options={'quality': 90},
    )


class Comment(TimeStampedModel):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

07_django/INSTA/posts/forms.py
from django import forms
from .models import Post, Image, Comment


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content',]


class ImageModelForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file', ]
        widgets = {
            'file': forms.FileInput(attrs={'multiple': True})
        }


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

07_django/INSTA/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest
from .models import Post, Image, HashTag
from .forms import PostModelForm, ImageModelForm, CommentModelForm


@login_required
@require_http_methods(['GET', 'POST'])
def create_post(request):
    # POST 방식으로 넘온 Data 를 ModelForm 에 넣는다.
    if request.method == 'POST':
        # POST 방식으로 넘온 Data 를 ModelForm 에 넣는다.
        # ModelForm(data, files) - default
        post_form = PostModelForm(request.POST)
        # Data 검증을 한다.
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            # Create HashTag => <input name='tags'>
            content = post_form.cleaned_data.get('content')
            words = content.split(' ') # 띄어쓰기 기준으로 split
            for word in words:
                if word[0] == '#':
                    word = word[1:]
                    tag = HashTag.objects.get_or_create(content=word) # (HashTagobj, True or False)
                    post.tags.add(tag[0])
                    if tag[1]:
                        messages.add_message(request, messages.SUCCESS, f'#{tag[0].content}태그를 처음으로 추가하셨어요! :)')
            for image in request.FILES.getlist('file'): # 여러 장의 사진은 리스트로 저장되어 들어온다.
                request.FILES['file'] = image
                image_form = ImageModelForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False) # ForeignKey 가 없는 상태
                    image.post = post
                    image.save()
            return redirect('posts:post_list')

    # GET 방식으로 요청이 오면,
    else:
        # 새로운 Post 용 form 을 만든다.
        post_form = PostModelForm()
    image_form = ImageModelForm()

    # 사용자에게 html 과 form을 만든다.
    return render(request, 'posts/form.html', {
        'post_form': post_form,
        'image_form': image_form,
    })


@login_required
@require_http_methods(['GET', 'POST'])
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user == request.user: # 지금 수정하려는 post 작성자가 요청 보낸 사람이냐?
        if request.method == 'POST':
            post_form = PostModelForm(request.POST, instance=post)
            if post_form.is_valid():
                post_form.save()
                # update HashTag
                post.tags.clear() # 기존 태그 다 날리기
                content = post_form.cleaned_data.get('content')
                words = content.split(' ')  # 띄어쓰기 기준으로 split
                for word in words:
                    if word[0] == '#':
                        word = word[1:]
                        tag = HashTag.objects.get_or_create(content=word)  # (HashTagobj, True or False)
                        post.tags.add(tag[0])
                return redirect('posts:post_list')
        else:
            post_form = PostModelForm(instance=post)
    else: # 작성자와 요청 보낸 user 가 다르다면
        # 403 : Forbidden 금지됨!
        return redirect('posts:post_list')

    return render(request, 'posts/form.html', {
        'post_form': post_form
    })


@require_GET
def post_list(request):
    if request.GET.get('next'):
        return redirect(request.GET.get('next'))
    posts = Post.objects.all()
    comment_form = CommentModelForm()

    return render(request, 'posts/list.html', {
        'posts': posts,
        'comment_form': comment_form,
    })


@login_required
@require_POST
def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment_form = CommentModelForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/insta/'))
    # TODO else: => What if comment is not valid?


@login_required
@require_POST
def toggle_like(request, post_id):
    if request.is_ajax():
        user = request.user
        post = get_object_or_404(Post, id=post_id)
        is_active = True
        # if post.like_users.filter(id=user.id): # 찾으면, [value] / 없으면 []
        if user in post.like_users.all():
            post.like_users.remove(user)
            is_active = False
        else:
            post.like_users.add(user)

        return JsonResponse({
            'likeCount': post.like_users.count(),
            'is_active': is_active,
        })
    else:
        return HttpResponseBadRequest()

@require_GET
def tag_posts_list(request, tag_name):
    tag = get_object_or_404(HashTag, content=tag_name)
    posts = tag.posts.all()
    comment_form = CommentModelForm()
    return render(request, 'posts/list.html', {'posts': posts, 'comment_form': comment_form, 'h1': f'#{tag}를 포함한 posts 입니다.'})

07_django/INSTA/posts/templates/posts/_post.html
<div class="card my-3">
    {% if post.image_set.all %}
        <div id="post{{ post.id }}" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in post.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#post{{ post.id }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post{{ post.id }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    {% else %}
        <img src="https://picsum.photos/600" alt="random-image" class="card-img-top"/>
    {% endif %}
    <div class="card-body">
        <p class="card-text">{{ post.content }}</p>
        <p class="d-flex justify-content-end">작성자 : <a href="{% url 'accounts:user_detail' post.user.username %}" class="text-dark">{{ post.user.username }}</a></p>
        {% if user == post.user %}
            <a href="{% url 'posts:update_post' post.id %}" class="btn btn-warning">수정</a>
        {% endif %}
    </div>

    <div class="card-body">
        <p class="card-text">좋아요 : <span id="like-count-{{ post.id }}">{{ post.like_users.count }}</span>개</p>
{#    좋아요 버튼 1#}
{#        <form action="{% url 'posts:toggle_like' post.id %}" method="POST">#}
{#            {% csrf_token %}#}
{#            <button type="submit" class="btn btn-primary">좋아요</button>#}
{#        </form>#}

{#    좋아요 2#}
    {% if user in post.like_users.all %}
        <i class="like-button fas fa-thumbs-up fa-2x activate" data-id="{{ post.id }}"></i>
    {% else %}
        <i class="like-button fas fa-thumbs-up fa-2x" data-id="{{ post.id }}"></i>
    {% endif %}


    </div>

    <div class="card-body">
        {% for comment in post.comment_set.all.reverse %}
            <p class="card-text">

                <a href="{% url 'accounts:user_detail' comment.user.username %}" class="text-dark"><strong>{{ comment.user.username }}</strong></a> : {{ comment.content }}
            </p>

        {% empty %}
            <p class="card-text">
                댓글을 달아주세요!
            </p>

        {% endfor %}
    </div>
    <div class="card-footer">
        <form action="{% url 'posts:create_comment' post.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form.content }}
            <input type="submit" class="btn btn-light">
        </form>
    </div>
</div>

07_django/INSTA/posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <h1>New post</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        {% if image_form %}
            {% bootstrap_form image_form show_label=False %}
        {% endif %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

07_django/INSTA/posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
    {% if h1 %}
        <h1>{{ h1 }}</h1>
    {% endif %}
    <section class="card-columns">
        {% for post in posts %}
            {% include 'posts/_post.html' with post=post comment_form=comment_form %}
        {% endfor %}
    </section>
{% endblock %}